"""
Internal Simulator — "what-if" rollout engine for the nawal brain.

Implements AbstractSimulator.  Before the agent acts, the simulator
imagines a short horizon of probable future states for each candidate
action and estimates the cumulative value of each branch.

Classical Phase 3 implementation
---------------------------------
Each rollout is generated by:

  1. Applying the action to the current world-state (rule-based delta).
  2. Scoring the resulting state with the ValuationLayer (if provided).
  3. Projecting forward by recursively applying simple transition rules.
  4. Summing discounted scores over the horizon.

Phase 6 upgrade hook (Quantum Imagination Engine)
---------------------------------------------------
Override ``simulate()`` with a quantum circuit that explores all
action branches in superposition (amplitude-encoded world states),
applies a parameterised world-model unitary, and measures to collapse
to the highest-value branch.  The ``best_action()`` method is unchanged.

Usage::

    vl  = ValuationLayer()
    sim = InternalSimulator(valuation_layer=vl, discount=0.9, horizon=3)

    scenarios = sim.simulate(
        current_state={"context": "user asked about capital city"},
        possible_actions=[
            {"type": "retrieve", "query": "capital city Belize"},
            {"type": "generate", "response": "I think it's Belmopan."},
        ],
        horizon=2,
        n_samples=3,
    )
    best = sim.best_action(scenarios)
"""

from __future__ import annotations

import copy
import random
import re
from dataclasses import dataclass, field
from typing import Any, Dict, List, Optional

from loguru import logger

from metacognition.interfaces import AbstractSimulator

# --------------------------------------------------------------------------- #
# Transition rules                                                             #
# --------------------------------------------------------------------------- #


def _apply_action(
    state: Dict[str, Any],
    action: Dict[str, Any],
) -> Dict[str, Any]:
    """
    Produce a new world-state by applying *action* to *state*.

    This is a simplified rule-based model.  Phase 6 replaces this with
    a learned world model or a quantum circuit.
    """
    new_state = copy.deepcopy(state)
    action_type = action.get("type", action.get("tool", "unknown"))

    if action_type in ("retrieve", "memory_read", "search"):
        # Retrieval enriches context
        new_state["context"] = (
            str(new_state.get("context", ""))
            + f" [retrieved: {action.get('query', '')}]"
        )
        new_state["memory_hits"] = new_state.get("memory_hits", 0) + 1

    elif action_type in ("generate", "respond"):
        new_state["response"] = action.get("response", action.get("text", ""))
        new_state["responded"] = True

    elif action_type in ("validate", "check"):
        new_state["validated"] = True

    elif action_type in ("execute", "act"):
        new_state["executed_steps"] = new_state.get("executed_steps", 0) + 1

    elif action_type == "noop":
        pass

    # Generic: append to history
    new_state.setdefault("action_log", []).append(action_type)
    return new_state


def _estimate_state_value(
    state: Dict[str, Any],
    valuation_layer: Optional[Any],
) -> float:
    """
    Scalar value of reaching *state*.

    If a ValuationLayer is available, score the response text.
    Otherwise, use heuristic signals.
    """
    if valuation_layer is not None:
        text = state.get("response", state.get("context", ""))
        try:
            scores = valuation_layer.score(
                [{"text": str(text)}],
                context=state,
            )
            return scores[0] if scores else 0.5
        except Exception as exc:
            logger.debug(f"InternalSimulator: valuation_layer.score raised: {exc}")

    # Heuristic: reward progress signals
    value = 0.5
    if state.get("responded"):
        value += 0.2
    if state.get("validated"):
        value += 0.1
    if state.get("memory_hits", 0) > 0:
        value += 0.05 * min(state["memory_hits"], 3)
    return min(1.0, value)


# --------------------------------------------------------------------------- #
# InternalSimulator                                                            #
# --------------------------------------------------------------------------- #


class InternalSimulator(AbstractSimulator):
    """
    Classical "what-if" rollout simulator.

    Args:
        valuation_layer : Optional ValuationLayer used to score states.
        discount        : Temporal discount factor γ ∈ (0, 1].
        horizon         : Default rollout depth (number of steps forward).
        n_samples       : Default samples per branch (adds stochastic noise).
        noise_scale     : Gaussian noise scale on value estimates.
    """

    def __init__(
        self,
        valuation_layer: Optional[Any] = None,
        discount: float = 0.9,
        horizon: int = 3,
        n_samples: int = 4,
        noise_scale: float = 0.05,
        seed: Optional[int] = None,
    ) -> None:
        self._vl = valuation_layer
        self.discount = discount
        self.default_horizon = horizon
        self.default_n_samples = n_samples
        self._noise_scale = noise_scale
        self._rng = random.Random(seed)

    # ------------------------------------------------------------------ #
    # AbstractSimulator implementation                                     #
    # ------------------------------------------------------------------ #

    def simulate(
        self,
        current_state: Dict[str, Any],
        possible_actions: List[Dict[str, Any]],
        horizon: Optional[int] = None,
        n_samples: Optional[int] = None,
    ) -> List[Dict[str, Any]]:
        """
        Generate imagined future scenarios for each action.

        Returns a list of scenario dicts, one per ``possible_actions`` entry::

            {
                "action":     dict,   # the triggering action
                "trajectory": [state1, state2, …],  # predicted states
                "value":      float,  # discounted cumulative value
                "samples":    int,    # number of rollout samples averaged
            }

        Phase 6 refactor note:
          Replace the loop below with a quantum circuit that puts all
          action branches in superposition before measuring.
        """
        h = horizon if horizon is not None else self.default_horizon
        s = n_samples if n_samples is not None else self.default_n_samples

        scenarios = []
        for action in possible_actions:
            cumulative_values: List[float] = []
            sample_trajectory: List[Dict[str, Any]] = []

            for sample_idx in range(s):
                value, traj = self._rollout(current_state, action, h)
                cumulative_values.append(value)
                if sample_idx == 0:  # keep first trajectory as representative
                    sample_trajectory = traj

            avg_value = sum(cumulative_values) / len(cumulative_values)

            scenarios.append(
                {
                    "action": action,
                    "trajectory": sample_trajectory,
                    "value": round(avg_value, 4),
                    "samples": s,
                }
            )

        logger.info(
            f"InternalSimulator: simulated {len(possible_actions)} actions "
            f"× {s} samples, horizon={h}"
        )
        return scenarios

    def best_action(
        self,
        simulations: List[Dict[str, Any]],
    ) -> Dict[str, Any]:
        """
        Return the action with the highest estimated value.

        Returns the first simulation if the list is empty.
        """
        if not simulations:
            return {"type": "noop"}
        best = max(simulations, key=lambda s: s.get("value", 0.0))
        logger.info(
            f"InternalSimulator best_action: "
            f"value={best['value']:.4f} action={best['action']}"
        )
        return best["action"]

    # ------------------------------------------------------------------ #
    # Internals                                                            #
    # ------------------------------------------------------------------ #

    def _rollout(
        self,
        initial_state: Dict[str, Any],
        first_action: Dict[str, Any],
        horizon: int,
    ) -> tuple[float, List[Dict[str, Any]]]:
        """
        Single stochastic rollout from *initial_state* taking *first_action*
        then following a simple continuation policy for *horizon-1* steps.

        Returns (discounted_cumulative_value, trajectory).
        """
        state = copy.deepcopy(initial_state)
        trajectory: List[Dict[str, Any]] = []
        total_value = 0.0
        gamma = 1.0  # will be multiplied by discount on each step

        for step in range(horizon):
            action = first_action if step == 0 else self._continuation_policy(state)
            state = _apply_action(state, action)
            step_value = _estimate_state_value(state, self._vl)

            # Add controlled noise for diversity across samples
            noise = self._rng.gauss(0, self._noise_scale)
            step_value = max(0.0, min(1.0, step_value + noise))

            total_value += gamma * step_value
            trajectory.append(copy.deepcopy(state))
            gamma *= self.discount

        return total_value, trajectory

    def _continuation_policy(self, state: Dict[str, Any]) -> Dict[str, Any]:
        """
        Minimal heuristic continuation policy:
        - If not yet responded → generate response
        - If not yet validated → validate
        - Else → noop
        """
        if not state.get("responded"):
            return {"type": "generate", "text": state.get("context", "")}
        if not state.get("validated"):
            return {"type": "validate"}
        return {"type": "noop"}
